### ISSUE TITLE
Missing mandatory fields error

### ISSUE THREAD

**Issue by capybarahero** [0x80/isolate-package#139]
Hi @0x80,
I'm getting the following issue after upgrading to v1.24.0: 

```
Package at (root)/<app_name> is missing mandatory fields: files. The "version" field is required for pack to execute, and the "files" field is required to declare what files should be included in the output. See the documentation for more details.
    at validateManifestMandatoryFields (file:///<file_path>/node_modules/.pnpm/isolate-package@1.24.0/node_modules/isolate-package/src/lib/manifest/validate-manifest.ts:40:11)
```

 I did what the documentation suggests, but (1) didn't work or (2) other rollup issues appeared, such as: 

```
[!] Error: Cannot find module '/<path>/isolated_module/rollup.config.js' imported from /<path>/.pnpm/rollup@4.46.1/node_modules/rollup/dist/shared/loadConfigFile.js
````
It works fine after rolling back to 1.23.0. 

Could you please review these latest changes and maybe add "files" as an optional flag on the config file instead?
Thanks again for this great package!

**Comment by 0x80** [comment]
Feel free to re-open if you have more info

**Comment by mashiro** [comment]
I’m still running into the same error on 1.26.1. It looks like the [internal packages strategy](https://github.com/0x80/isolate-package?tab=readme-ov-file#the-internal-packages-strategy) hasn’t been working since 1.24. Since this is an internal package, I don’t think files should need to be defined.

**Comment by 0x80** [comment]
Ah, right, I haven't been using that pattern anywhere anymore. Have you tried it with an empty `files` array?
